min_version = "2026.6.13"

[settings]
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.codex/config.toml" = { source = "config/codex/config.toml" }
"~/.gitconfig" = { source = "config/git/.gitconfig" }
"~/.zprofile" = { source = "config/zsh/.zprofile" }
"~/.zshrc" = { source = "config/zsh/.zshrc" }
"~/.config/mise/config.toml" = { source = "config/mise/config.toml" }
"~/.config/starship.toml" = { source = "config/starship.toml" }
"~/Library/Application Support/Code/User/settings.json" = { source = "config/vscode/settings.json" }
"~/.warp/settings.toml" = { source = "config/warp/settings.toml" }

[tools]
deno = "latest"
java = "latest"
node = "latest"
purescript = "latest"
python = "latest"
ruby = "latest"
"npm:oxfmt" = { version = "latest", depends = "node" }
"npm:oxlint" = { version = "latest", depends = "node" }
"npm:purty" = { version = "latest", depends = "node" }
"npm:spago" = { version = "latest", depends = "node" }
"npm:mystmd" = { version = "latest", depends = "node" }
