[tools]
deno = "latest"
dotnet = "latest"
eza = "latest"
gh = "latest"
ghcup = "latest"
gleam = "latest"
helix = "latest"
lefthook = "latest"
java = "latest"
node = "latest"
opam = "latest"
purescript = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
starship = "latest"
sheldon = "latest"
shfmt = "latest"
taplo = "latest"
typst = "latest"
zoxide = "latest"
oxfmt = "latest"
oxlint = "latest"
purty = "latest"
spago = "latest"
"npm:mystmd" = { version = "latest", depends = "node" }
